---
title: "Download somatic mutation data from GDC, then apply test()"
output: rmarkdown::html_document
vignette: >
  %\VignetteIndexEntry{Introduction}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

This script provides an example of how to download mutation data from the GDC database for GBM (glioblastoma) and
how to apply test() to test the drugs in your drug response dataset to each mutation to identify biomarkers that enrich for drug response.

Download mutation data for your cancer of interest from GDC database <h2>
```{r}
library(TCGAbiolinks)
#GDCquery_Maf() downloads MAF (mutation annotation files) for glioblastoma (GBM).
#Other disease abbreviations include: "ACC", "BLCA", "BRCA", "CESC", "CHOL", "COAD", "COADREAD", "DLBC", "GBM", "GBMLGG", "HNSC", "KICH", "KIPAN", #"KIRC", "KIRP", "LAML", "LGG", "LIHC", "LUAD", "LUSC", "MESO", "OV", "PAAD", "PCPG", "PRAD", "READ", "SARC", "SKCM", "STAD", "STES", "TGCT", "THCA", #"THYM", "UCEC", "UCS", "UVM"
maf<-GDCquery_Maf("GBM", pipelines = "muse")
```

Apply test()
```{r}
#Determine test() parameters.

#Determine the parameters of the test() function...
#Set the drug_prediction parameter.
#Make sure rownames() are drugs, and colnames() are samples. Also make sure this data is a data frame.
drug_prediction<-as.data.frame(read.table('./DrugPredictions.txt', header=TRUE, row.names=1))
#In this example, I had to replace the '.' in the names of these TCGA samples with '-' so that they are of the same form as samples in the mutation  data (you may not have to do this).
colnames(drug_prediction)<-gsub(".", "-", colnames(drug_prediction), fixed=T)

#Set the data parameter.
#Make sure this data is a data frame and that colnames() are samples.
data<-as.data.frame(maf)

#Determine the number of samples you want the CNVs to be amplified in. The default is 10.
n=10

#Indicate whether or not you would like to test cnv data. If TRUE, you will test cnv data. If FALSE, you will test mutation data.
cnv=FALSE

library(pRRopheticplus)

#Apply test()
test(drug_prediction=drug_prediction, data=data, n=n, cnv=cnv)
```

