---
title: "Control for GLDS (general levels of drug sensitivity) in pre-clinical samples for biomarker discovery"
output: rmarkdown::html_document
vignette: >
  %\VignetteIndexEntry{Introduction}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

This script provides an example of how to control for GLDS in pre-clinical biomarker discovery. Controlling for GLDS is important because
variability in GLDS is evient in cancer cell lines, and controlling for this variability improves cancer biomarker discovery.

Apply completeMatrix()
```{r}
#if (!require("BiocManager"))
#  install.packages("BiocManager")
#BiocManager::install('TCGAbiolinks')

library(pRRopheticplus)

#Set parameters of completeMatrix()
nPerms=50
trainingPtype = readRDS(file = "GDSC2_Res.rds")
dim(trainingPtype) #805 198 ...there are some NA values so prcomp() will complain.
senMat=trainingPtype

#Apply completeMatrix()
#This function will create a file called complete_matrix_output.txt in your working directory.
#This file is used as input in the next function.
#Read GDSCv2's drug sensitivity matrix.
#library(glmnet)
#completeMatrix(trainingPtype)
```

Apply the GLDS function.
```{r}
setwd('C:/Users/Danielle/Desktop')
#_______________________________________________________________________________________________________________________________________________________________
#'@param drugMat A matrix of drug sensitivity data. rownames() are pre-clinical samples, and colnames() are drug names.

library(readxl)
cellLineDetails<-read_excel('Cell_Lines_Details.xlsx')

#I read the response data through completeMatrix() because there were some NA values.
#NA values in the response data will cause a problem when you apply prcomp().
cm<-read.table('complete_matrix_output GDSCv2.txt', header=TRUE, row.names=1) #Now, there are no NA values.
rownames(cm) #Cosmic identifiers are used for cell names.

#Replace the rownames of cm with cell line names. Right now, they are cosmic ids.
#This will require using GDSC's cell line details file (which maps cosmic ids to cell line names).
newRows <- substring(rownames(cm),8) #Remove 'COSMIC'...keep the numbers after COSMIC.
newRows #Just the cosmic id...doesn't have 'COSMIC_...' in front of the number.
as.vector(unlist(cellLineDetails[,2]))
indices<-match(as.numeric(newRows), as.vector(unlist(cellLineDetails[,2]))) #Refer to the cell line details file to make this replacement.
newNames<-as.vector(unlist(cellLineDetails[,1]))[indices] #Reports the corresponding cell line names
rownames(cm)<-newNames

#Fix the drug names in the cm object so that it's just the name (remove those extra numbers/identifiers at the end).
#fixme2.xlsx contained the colnames of cm in the correct order, but with the extra identifiers removed.
fix2<-read_excel('fixme2.xlsx')
fix2<-as.vector(unlist(fix2[,1]))
colnames(cm)<-fix2

drugMat<-cm
dim(drugMat) #805 samples vs. 198 drugs
#_______________________________________________________________________________________________________________________________________________________________
#'@param markerMat A matrix containing the data for which you are looking for an association with drug sensitivity (e.g. a matrix of somatic mutation data). rownames() are marker names (e.g. gene names), and colnames() are samples.
#GDSCv2's updated mutation data, pan cancer, both CNV and coding variant.
mutationMat<-read.csv('C:/Users/Danielle/Desktop/GDSC2_Pan_Both.csv')
mutationMat<-mutationMat[,c(1,6,7)]
colnames(mutationMat) #[1] "cell_line_name"  "genetic_feature" "is_mutated"    
vec<-c()
for (i in 1:nrow(mutationMat)){
  vec[i]<-paste(mutationMat[i,1],mutationMat[i,2], sep=' ')
}
nonDupIndices<-match(unique(vec), vec)
mutationMat2<-mutationMat[nonDupIndices,]
library(tidyverse)
(mutationMat2[,2]) != "" #Some gene muts are blank! Remove them. This causes problems in pivot_wider.
NondupsIndices<-(mutationMat2[,2]) != ""
mutationMat3<-mutationMat2[NondupsIndices,]
mutationMat4<-mutationMat3 %>%
  pivot_wider(names_from=genetic_feature,
              values_from=is_mutated)
mutationMat4<-as.matrix(mutationMat4)
rownames(mutationMat4)<-as.vector(unlist(mutationMat4[,1])) #Make cell lines the rownames...right now they are column 1.
mutationMat<-as.matrix(t(mutationMat4[,-1]))
mutationMat5<-mutationMat
mutationMat5<-apply(mutationMat5, 2, as.numeric)
rownames(mutationMat5)<-rownames(mutationMat)
mutationMat<-mutationMat5
dim(mutationMat) #1315 1389
# replace all non-finite values with 0
mutationMat[!is.finite(mutationMat)] <- 0
markerMat<-mutationMat
dim(markerMat) #1315 1389

#'@param drugRelatedness A list, which for each drug, contains a vector of 1's and 0's, indicating whether the drugs are related (e.g. if both drugs were an inhibitor of ERBB2, that position would contain a 1).
#Bulk data download, all compounds screened, compounds-annotation.
#Note: I had to change some drug names in this file so that they matched colnames of cm.
#Ex: replace - with . (small modifications like that).
drugRelatedness <- read.csv("screened_compunds_rel_8.2.csv")
drugRelatedness<-drugRelatedness[,c(3,6)]
dim(drugRelatedness) #518 2
colnames(drugRelatedness) #[1] "DRUG_NAME"      "TARGET_PATHWAY"

gldsCorrectedAssoc(drugMat,
                   drugRelatedness,
                   markerMat,
                   minMuts=5,
                   additionalCovariateMatrix=NULL,
                   threshold=0.7)
```
